# Generated by Django 5.0.7 on 2024-11-05 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='account_name',
            new_name='アカウント名',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='gender',
            new_name='性別',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='birth_date',
            new_name='生年月日',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='avatar',
            new_name='画像',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='自己紹介',
        ),
    ]
