# Generated by Django 5.0.7 on 2024-11-13 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
