# Generated by Django 5.0.7 on 2024-11-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_account_name_userprofile_アカウント名_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='ユーザー',
        ),
    ]
