# Generated by Django 5.0.7 on 2024-12-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_hashtag_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(related_name='posts', to='app.hashtag'),
        ),
    ]
