# Generated by Django 5.0.7 on 2024-11-05 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userprofile_性別_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ユーザー',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
