# Generated by Django 5.0.7 on 2024-12-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_post_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='items',
            field=models.ManyToManyField(related_name='posts', to='app.item'),
        ),
    ]
