# Generated by Django 5.0.7 on 2024-11-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='image',
            field=models.ImageField(default='default_images/default.png', upload_to='wishlist_images/'),
        ),
    ]
