# Generated by Django 5.0.7 on 2024-11-06 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_userprofile_ユーザー'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
