# Generated by Django 5.0.7 on 2024-12-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('white', '白'), ('black', '黒'), ('gray', 'グレー'), ('brown', '茶'), ('beige', 'ベージュ'), ('green', '緑'), ('blue', '青'), ('purple', '紫'), ('yellow', '黄'), ('pink', 'ピンク'), ('red', '赤'), ('orange', 'オレンジ'), ('other', 'その他')], default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='genre',
            field=models.CharField(choices=[('tops', 'トップス'), ('skirts', 'スカート'), ('outer', 'アウター'), ('onepiece', 'ワンピース'), ('pants', 'パンツ'), ('hat', '帽子'), ('maternity', 'マタニティ'), ('baby', 'ベビー'), ('other', 'その他')], default='tops', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('50~60', '50~60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100'), ('110', '110'), ('120', '120'), ('130', '130'), ('140', '140')], default='M', max_length=10),
        ),
    ]
