# Generated by Django 5.0.7 on 2024-11-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_wishlistitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='image',
            field=models.ImageField(blank=True, default='wishlist_images/default.png', null=True, upload_to='wishlist_images/'),
        ),
    ]
