# Generated by Django 5.0.7 on 2024-11-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_wishlistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
