# Generated by Django 5.0.7 on 2024-12-19 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_item_color_item_genre_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='clothes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.clothes'),
        ),
    ]
