# Generated by Django 5.0.7 on 2024-11-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_wishlistitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('50~60', '50~60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100'), ('110', '110'), ('120', '120'), ('130', '130'), ('140', '140')], max_length=10)),
                ('genre', models.CharField(choices=[('tops', 'トップス'), ('skirts', 'スカート'), ('outer', 'アウター'), ('onepiece', 'ワンピース'), ('pants', 'パンツ'), ('hat', '帽子'), ('maternity', 'マタニティ'), ('other', 'その他')], max_length=50)),
                ('color', models.CharField(choices=[('white', '白'), ('black', '黒'), ('gray', 'グレー'), ('brown', '茶'), ('beige', 'ベージュ'), ('green', '緑'), ('blue', '青'), ('purple', '紫'), ('yellow', '黄'), ('pink', 'ピンク'), ('red', '赤'), ('orange', 'オレンジ'), ('other', 'その他')], max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clothes_images/')),
            ],
        ),
    ]
