# Generated by Django 5.0.7 on 2024-12-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_item_clothes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='posts', to='app.item'),
        ),
    ]
