# Generated by Django 5.0.7 on 2024-11-11 03:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_wishlistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='アカウント名',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='自己紹介',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='生年月日',
            new_name='birth_of_date',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='性別',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='画像',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='ユーザー',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='値段',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='ブランド',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='メモ',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='商品URL',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='画像',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wishlist_images/'),
        ),
    ]
