# Generated by Django 5.0.7 on 2024-11-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_clothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='gender',
            field=models.CharField(choices=[('Male', '男性'), ('Female', '女性'), ('Unisex', 'ユニセックス')], default='Unisex', max_length=10),
        ),
    ]
