# Generated by Django 5.0.7 on 2024-11-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_clothes_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='gender',
            field=models.CharField(choices=[('Male', '男性'), ('Female', '女性')], default='Unisex', max_length=10),
        ),
    ]
