# Generated by Django 5.0.7 on 2024-11-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_アカウント名_userprofile_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='notes',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='product_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
