# Generated by Django 5.0.7 on 2025-01-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_hashtag_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clothes',
            field=models.ManyToManyField(blank=True, related_name='posts', to='app.clothes'),
        ),
    ]
