# Generated by Django 5.0.7 on 2024-11-26 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_clothes_color_alter_clothes_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clothes',
            name='gender',
            field=models.CharField(choices=[('Male', '男性'), ('Female', '女性'), ('Other', 'その他')], default='Unisex', max_length=10),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='genre',
            field=models.CharField(choices=[('tops', 'トップス'), ('skirts', 'スカート'), ('outer', 'アウター'), ('onepiece', 'ワンピース'), ('pants', 'パンツ'), ('hat', '帽子'), ('maternity', 'マタニティ'), ('baby', 'ベビー'), ('other', 'その他')], max_length=20),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/images/')),
                ('caption', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hashtags', models.ManyToManyField(blank=True, to='app.hashtag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
