# Generated by Django 5.0.7 on 2024-12-24 05:53

# Generated by Django 5.0.7 on 2024-12-24 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_default_user(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Hashtag = apps.get_model('app', 'Hashtag')
    
    # デフォルトユーザーを取得または作成
    default_user, created = User.objects.get_or_create(
        username="default_user", 
        email="default@example.com"
    )
    
    # 既存のHashtagのuserフィールドをデフォルトユーザーに設定
    for hashtag in Hashtag.objects.filter(user=None):
        hashtag.user = default_user
        hashtag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_hashtag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_default_user),
        migrations.AlterField(
            model_name='hashtag',
            name='user',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
