# Generated by Django 5.0.7 on 2024-11-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_hashtag_alter_clothes_gender_alter_clothes_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='items/images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='items',
            field=models.ManyToManyField(blank=True, to='app.item'),
        ),
    ]
