# Generated by Django 5.0.7 on 2024-11-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_item_remove_post_hashtags_post_is_public_post_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='account',
            field=models.CharField(default='default_account', max_length=50),
        ),
    ]
