# Generated by Django 5.0.7 on 2025-01-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_post_items_clothes_user_item_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
