# Generated by Django 5.0.7 on 2024-11-27 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_post_user_post_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
