# Generated by Django 5.0.7 on 2025-01-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_clothes_updated_at_post_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='posts', to='app.item'),
        ),
    ]
