# Generated by Django 5.0.7 on 2024-12-24 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_hashtag_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='user',
        ),
    ]
