# Generated by Django 5.0.7 on 2025-01-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_item_post_post_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
