# Generated by Django 5.0.7 on 2024-11-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_user_created_at_user_updated_at_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='account',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
