# Generated by Django 5.0.7 on 2025-01-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_user_account_name_user_bio_user_birth_of_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='items',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
