# Generated by Django 5.0.7 on 2024-11-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_user_options_remove_post_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account',
        ),
    ]
