# Generated by Django 5.0.7 on 2025-01-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_post_items_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default-profile.png', null=True, upload_to='profile_images/'),
        ),
    ]
