# Generated by Django 5.0.7 on 2025-01-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_hashtag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_images/default-profile.png', upload_to='profile_images/'),
        ),
    ]
