# Generated by Django 5.0.7 on 2025-02-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_post_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/default-profile.png', null=True, upload_to='clothes_images/'),
        ),
    ]
