# Generated by Django 5.0.7 on 2025-02-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_clothes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.ImageField(blank=True, default='clothes_images/default-clothes.png', null=True, upload_to='clothes_images/'),
        ),
    ]
