# Generated by Django 5.0.7 on 2025-02-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_clothes_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
