# Generated by Django 5.0.7 on 2025-02-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
