# Generated by Django 5.0.7 on 2025-02-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='default-profile.png', null=True, upload_to='profile_images/'),
        ),
    ]
