# Generated by Django 5.0.7 on 2025-02-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_wishlistitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='image',
            field=models.ImageField(default='wishlist_images/default.png', upload_to='wishlist_images/'),
        ),
    ]
